version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Updating to corretto21
  build:
    commands:
      - echo Building the project with Maven...
      - cd root
      - mvn clean install
  post_build:
    commands:
      - echo Build complete.
      - mvn test
artifacts:
  files:
    - root/target/root-0.0.1-SNAPSHOT.jar
