version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Updating to corretto21
  build:
    commands:
      - echo Building the project with Maven...
      - cd root
      - mvn clean install
  post_build:
    commands:
      - echo Build complete.
      - mvn test
      - echo Moving artifact to the root of the deployment bundle...
      - cp root/target/root-0.0.1-SNAPSHOT.jar ./application.jar
      - echo "web: java -jar application.jar" > Procfile
artifacts:
  files:
    - root/target/root-0.0.1-SNAPSHOT.jar
